# Generated by Django 5.1.5 on 2025-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
