# Generated by Django 5.1.5 on 2025-01-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_trainee_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainee',
            new_name='Trainee_model',
        ),
    ]
