# Generated by Django 5.1.5 on 2025-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_trainee_trainee_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee_model',
            name='domain',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
