# Generated by Django 5.1.5 on 2025-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_trainee_model_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee_model',
            name='domain',
            field=models.CharField(max_length=200),
        ),
    ]
