# Generated by Django 5.1.5 on 2025-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_trainee_model_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue_name', models.CharField(max_length=200)),
                ('trainees_enrolled', models.PositiveIntegerField()),
                ('faculty', models.CharField(max_length=200)),
            ],
        ),
    ]
