# Generated by Django 5.1.5 on 2025-01-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_model',
        ),
    ]
