# Generated by Django 5.1.5 on 2025-01-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_faculty_model_delete_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_model',
            old_name='course_id',
            new_name='id',
        ),
    ]
